name: Docker build & release

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      - uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image ğŸš¢
        uses: docker/build-push-action@v5
        with:
          context: indico/worker
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ env.VERSION }}
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/indico:${{ env.VERSION }}
            getindico/indico:${{ env.VERSION }}
          outputs: type=oci,dest=/tmp/indico-image.tar

      - name: Test if Indico works ğŸ§ª
        run: |
          docker load --input /tmp/indico-image.tar
          cp indico.env.sample indico.env
          sed -i -E 's/image: getindico\/indico:latest/image: getindico\/indico:${{ env.VERSION }}/' docker-compose.yml
          ./test.sh

      - name: Upload build artifact ğŸ”¼
        uses: actions/upload-artifact@v3
        with:
          name: indico-image
          path: /tmp/indico-image.tar

  publish-ghcr:
    name: Publish to GHCR ğŸ™
    needs: build
    runs-on: ubuntu-22.04
    environment: publish-ghcr
    permissions:
      packages: write
    steps:
      - name: Download build artifact ğŸ”½
        uses: actions/download-artifact@v3
        with:
          name: indico-image
          path: /tmp/

      - name: Import image
        run: docker load --input /tmp/indico-image.tar

      - name: Log in to GHCR ğŸ”‘
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker image ğŸš¢
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/indico:${{ env.VERSION }}

  publish-dockerhub:
    name: Publish to Docker Hub ğŸš¢
    needs: build
    runs-on: ubuntu-22.04
    environment: publish-dockerhub
    steps:
      - name: Download build artifact ğŸ”½
        uses: actions/download-artifact@v3
        with:
          name: indico-image
          path: /tmp/

      - name: Import image
        run: docker load --input /tmp/indico-image.tar

      - name: Log in to Docker Hub ğŸ”‘
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image ğŸš¢
        run: |
          docker push getindico/indico:${{ env.VERSION }}
